src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    const SUCCESS_REGISTER = 'Post created successfully.';
    const NOT_FOUND = 'Post not found.';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cover_image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     */
    private $user;

    /**
     * Post constructor.
     */
    public function __construct()
    {
        $this->created_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->cover_image;
    }

    public function setCoverImage(?string $cover_image): self
    {
        $this->cover_image = $cover_image;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(Request $request): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $posts = $entityManager->getRepository(Post::class)->getPosts();

        return $this->render('home/index.html.twig', [
            'posts' => $posts,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'layouts/app.html.twig' %}

{% block body %}
    {% for post in posts %}
        <div class="d-flex justify-content-center">
            <a class="text-decoration-none text-dark" href="{{ path('post_show', {id: post.id}) }}">
                <div class="card shadow mb-5" style="width: 35rem;">
                    {% if post.coverImage == null %}
                        <img class="card-img-top" src="{{ asset('images/cover.jpg') }}" alt="{{ post.title }}">
                    {% else %}
                        <img class="card-img-top" src="{{ asset('uploads/cover_images/'~post.coverImage) }}" alt="{{ post.title }}">
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.body | slice(0, 120) }}...</p>
                        <p class="card-text"><small class="text-muted">{{ post.createdDate | date }}</small></p>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}